- Located on quiet one way street with free on-street parking
- Spacious Kitchen comes equipped with Full Size Stove, Fridge, Dishwasher, and Garbage disposal
- New bathroom vanity
- Freshly painted throughout
- Laminate Flooring in Kitchen and Bedrooms
- Freshly shampooed carpet in living room
- High Ceilings and Lots of Natural Light
- 2 Generous Living Areas. 
- Central Air Conditioning
- Ground floor convenience - no stairs!
- Locked front and rear entry
- Washer and Dryer in the Building (Coin-Op), on the same floor
- Communal outdoor courtyard behind building, private door to courtyard

